### ISSUE TITLE
GitHub Issue: Fix UI Error Loading Product and Environment Details in Dashboard

### ISSUE THREAD

**Issue by Sam123ben** [Sam123ben/IDP-Integrated-Developer-Platform#9]
**Goal:**  
Resolve the UI issue preventing the product and environment details from loading in the dashboard sidebar.

---

### **Description:**

When accessing the dashboard, the UI fails to load the product and environment details as expected. The sidebar intended to display this information shows an error instead:

```Error fetching infra types: TypeError: Failed to fetch
    at _callee2$ (api.js:62:18)
    at tryCatch (api.js:9:1062)
    at Generator.eval (api.js:9:3008)
    at Generator.eval [as next] (api.js:9:1699)
    at asyncGeneratorStep (api.js:10:70)
    at _next (api.js:11:163)
    at eval (api.js:11:299)
    at new Promise (<anonymous>)
    at eval (api.js:11:90)
    at fetchInfraTypes (api.js:88:18)
```

This error message indicates a failure in fetching infrastructure types from the backend, which results in the sidebar not displaying the available products and environments. The expected UI layout (as shown in the second screenshot) should include a list of products (e.g., "Product 1" and "Product 2") with associated environment options like "DEV", "QA", "CONSULT", etc.

### **Tasks:**

1. **Investigate the API Call to `/api/internal-env-details`:**
   - Verify that the frontend API call to `fetchInfraTypes` is correctly reaching the backend endpoint.
   - Check the endpoint URL, headers, and network requests to confirm there are no CORS or network-related issues.

2. **Check Backend Response:**
   - Ensure that the backend server is running and accessible.
   - Confirm that the `/api/internal-env-details` endpoint is functioning correctly and returning data as expected.
   - Check if there are any errors in the backend logs that could be causing the issue.

3. **Enhance Error Handling and Logging in Frontend:**
   - Update the frontend code to provide clearer error messages when the fetch fails.
   - Log the exact response status and error details for easier debugging.

4. **Test the UI with Expected Output:**
   - Once fixed, verify that the sidebar displays products and environments as expected, similar to the layout in the provided screenshot (right image).
   - Ensure that the information updates correctly based on different selections.

---

### **Acceptance Criteria:**

- [ ] The `/api/internal-env-details` API call successfully retrieves data from the backend without errors.
- [ ] The UI sidebar correctly displays the list of products and associated environments (e.g., "DEV", "QA").
- [ ] Improved error handling and logging are added in the frontend to provide clear feedback in case of future fetch issues.
- [ ] The UI matches the expected layout as shown in the screenshot, with product and environment details visible.

---

### **Commit Message**

Once this issue is addressed, use the following commit message:

```plaintext
fix: Resolve UI error for loading product and environment details in dashboard

![image](https://github.com/user-attachments/assets/65dfcb33-c870-460b-a5e6-e63329edacee)

**Comment by Sam123ben** [comment]
Fixed the issue

![image](https://github.com/user-attachments/assets/f9408242-716f-4bd5-9046-c432a71b22fe)
